from setuptools import setup, find_packages

setup(
    name="kubrik-ai",
    version="0.1.0",
    description="The Language Model for Data - Intelligent SQL routing and generation",
    author="KubrikAI Team",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "sqlglot>=20.0.0",
        "sqlparse>=0.4.2",
        "psycopg2-binary>=2.9.0",
        "pymysql>=1.0.0",
        "google-cloud-bigquery>=3.0.0",
        "snowflake-connector-python>=3.0.0",
        "sentence-transformers>=2.2.0",
        "transformers>=4.20.0",
        "torch>=1.12.0",
        "fastapi>=0.95.0",
        "uvicorn>=0.20.0",
        "websockets>=11.0.0",
        "structlog>=22.0.0",
        "prometheus-client>=0.16.0",
        "pydantic>=1.10.0",
        "pyyaml>=6.0",
        "pytest>=7.0.0",
        "pytest-asyncio>=0.21.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)